-- SQLite

CREATE TABLE IF NOT EXISTS meme (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    url TEXT
);

CREATE TABLE IF NOT EXISTS caption (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  text TEXT NOT NULL,
  memeId INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS rounds (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userId INTEGER NOT NULL,
    memeId INTEGER NOT NULL,
    memeUrl VARCHAR(255) NOT NULL,
    isCorrect BOOLEAN NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES user(id)
    FOREIGN KEY (memeId) REFERENCES meme(id)
);

